# Generated by Django 4.1.7 on 2023-03-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(unique=True, verbose_name='医生工号')),
                ('doctor_name', models.CharField(max_length=65, verbose_name='医生姓名')),
                ('doctor_photo', models.FileField(blank=True, null=True, upload_to='static/hospital/%Y/%m/%d/', verbose_name='医生照片')),
                ('doctor_age', models.SmallIntegerField(blank=True, max_length=100, null=True, verbose_name='医生年龄')),
                ('doctor_department', models.CharField(max_length=60, verbose_name='所属科室')),
                ('doctor_sex', models.BinaryField(choices=[(0, '女性'), (1, '男性')], verbose_name='医生性别')),
                ('doctor_describe', models.TextField(max_length=200, verbose_name='医生介绍')),
                ('doctor_title', models.CharField(max_length=60, verbose_name='医生职称')),
                ('doctor_telephone', models.CharField(max_length=11, verbose_name='医生电话')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '医生名单',
                'verbose_name_plural': '医生名单',
            },
        ),
    ]
