# Generated by Django 4.1.7 on 2023-03-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctormanage_doctor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormanage',
            name='doctor_department',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='所属科室'),
        ),
        migrations.AlterField(
            model_name='doctormanage',
            name='doctor_describe',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='医生介绍'),
        ),
        migrations.AlterField(
            model_name='doctormanage',
            name='doctor_sex',
            field=models.BinaryField(blank=True, choices=[(0, '女性'), (1, '男性')], null=True, verbose_name='医生性别'),
        ),
        migrations.AlterField(
            model_name='doctormanage',
            name='doctor_telephone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='医生电话'),
        ),
        migrations.AlterField(
            model_name='doctormanage',
            name='doctor_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='医生职称'),
        ),
    ]
