# Generated by Django 4.1.7 on 2023-03-18 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_doctormanage_doctor_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormanage',
            name='doctor_age',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)], verbose_name='医生年龄'),
        ),
        migrations.AlterField(
            model_name='doctormanage',
            name='doctor_sex',
            field=models.CharField(blank=True, choices=[('0', '女性'), ('1', '男性')], max_length=2, null=True, verbose_name='医生性别'),
        ),
    ]
