# Generated by Django 4.1.7 on 2023-03-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_doctormanage_doctor_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField(unique=True, verbose_name='医院编号')),
                ('hospital_name', models.CharField(max_length=65, verbose_name='医院名称')),
                ('hospital_address', models.CharField(max_length=65, verbose_name='医院地址')),
                ('hospital_telephone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('hospital_describe', models.TextField(max_length=200, verbose_name='医院介绍')),
                ('hospital_SoftLicense', models.IntegerField(default=0, verbose_name='授权总次数')),
                ('hospital_SoftLicense_used', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '医院名单',
                'verbose_name_plural': '医院名单',
            },
        ),
        migrations.DeleteModel(
            name='DoctorManage',
        ),
    ]
