# Generated by Django 4.1.7 on 2023-03-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_hospitalmanage_delete_doctormanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmanage',
            name='hospital_SoftLicense',
            field=models.IntegerField(default=0, verbose_name='License授权总次数'),
        ),
        migrations.AlterField(
            model_name='hospitalmanage',
            name='hospital_SoftLicense_used',
            field=models.IntegerField(default=0, verbose_name='License已使用次数'),
        ),
    ]
