# Generated by Django 4.1.7 on 2023-03-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_hospitalmanage_hospital_softlicense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmanage',
            name='hospital_address',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='医院地址'),
        ),
        migrations.AlterField(
            model_name='hospitalmanage',
            name='hospital_describe',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='医院介绍'),
        ),
        migrations.AlterField(
            model_name='hospitalmanage',
            name='hospital_telephone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话'),
        ),
    ]
