# Generated by Django 4.1.7 on 2023-03-25 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_hospitalmanage_hospital_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmanage',
            name='hospital_SoftLicense',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='License授权总次数'),
        ),
        migrations.AlterField(
            model_name='hospitalmanage',
            name='hospital_SoftLicense_used',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='License已使用次数'),
        ),
    ]
