# Generated by Django 4.1.7 on 2023-03-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_hospitalmanage_hospital_softlicense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmanage',
            name='create_by',
            field=models.CharField(default='root', max_length=64, verbose_name='购买人'),
        ),
        migrations.AddField(
            model_name='hospitalmanage',
            name='update_by',
            field=models.CharField(default='root', max_length=64, verbose_name='更新人'),
        ),
    ]
