# Generated by Django 4.0 on 2023-04-08 09:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_hospitalmanage_create_by_hospitalmanage_update_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmanage',
            name='hospital_describe',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True, verbose_name='医院介绍'),
        ),
    ]
