# Generated by Django 2.2.28 on 2023-05-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_auto_20230429_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmanage',
            name='hospital_people',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='联系人'),
        ),
    ]
