# Generated by Django 4.1.7 on 2023-03-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmanage',
            name='model_link',
            field=models.FileField(blank=True, null=True, upload_to='static/upload/', verbose_name='模型链接'),
        ),
    ]
