# Generated by Django 4.1.7 on 2023-03-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_classification', '0002_modelmanage_model_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmanage',
            name='model_link',
            field=models.FileField(blank=True, null=True, upload_to='static/upload/%Y/%m/%d/', verbose_name='模型链接'),
        ),
    ]
