# Generated by Django 4.1.7 on 2023-03-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_classification', '0003_alter_modelmanage_model_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelmanage',
            options={'verbose_name': '模型列表', 'verbose_name_plural': '模型列表'},
        ),
        migrations.AlterField(
            model_name='modelmanage',
            name='model_describe',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='模型描述'),
        ),
    ]
