# Generated by Django 4.1.7 on 2023-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_classification', '0004_alter_modelmanage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelmanage',
            name='model_link',
        ),
        migrations.AddField(
            model_name='modelmanage',
            name='create_by',
            field=models.CharField(default='root', max_length=64, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='modelmanage',
            name='model_author',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='模型作者'),
        ),
        migrations.AddField(
            model_name='modelmanage',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='static/upload/%Y/%m/%d/', verbose_name='模型文件'),
        ),
        migrations.AddField(
            model_name='modelmanage',
            name='model_type',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='模型类型'),
        ),
        migrations.AddField(
            model_name='modelmanage',
            name='model_version',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='模型版本'),
        ),
        migrations.AddField(
            model_name='modelmanage',
            name='update_by',
            field=models.CharField(default='root', max_length=64, verbose_name='更新人'),
        ),
    ]
