# Generated by Django 4.1.7 on 2023-03-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_classification', '0005_remove_modelmanage_model_link_modelmanage_create_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmanage',
            name='model_link',
            field=models.URLField(blank=True, max_length=65, null=True, verbose_name='模型链接'),
        ),
    ]
