# Generated by Django 4.0 on 2023-04-08 09:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_classification', '0006_modelmanage_model_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmanage',
            name='model_describe',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True, verbose_name='模型描述'),
        ),
    ]
