# Generated by Django 4.1.7 on 2023-03-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(unique=True, verbose_name='患者编号')),
                ('patient_name', models.CharField(max_length=65, verbose_name='患者姓名')),
                ('patient_age', models.SmallIntegerField(blank=True, max_length=100, null=True, verbose_name='患者年龄')),
                ('patient_sex', models.BinaryField(choices=[(0, '女性'), (1, '男性')], verbose_name='患者性别')),
                ('patient_department', models.CharField(max_length=60, verbose_name='挂号科室')),
                ('patient_describe', models.TextField(max_length=200, verbose_name='患者描述')),
                ('patient_photo', models.FileField(blank=True, null=True, upload_to='static/patient/%Y/%m/%d/', verbose_name='诊断影片')),
                ('patient_telephone', models.CharField(max_length=11, verbose_name='患者电话')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '患者名单',
                'verbose_name_plural': '患者名单',
            },
        ),
    ]
