# Generated by Django 4.1.7 on 2023-03-18 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patientmanage_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmanage',
            name='patient_age',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)], verbose_name='患者年龄'),
        ),
        migrations.AlterField(
            model_name='patientmanage',
            name='patient_sex',
            field=models.CharField(blank=True, choices=[('0', '女性'), ('1', '男性')], max_length=2, null=True, verbose_name='患者性别'),
        ),
    ]
