# Generated by Django 4.1.7 on 2023-03-18 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patientmanage_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmanage',
            name='patient_age',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='患者年龄'),
        ),
    ]
