# Generated by Django 4.1.7 on 2023-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patientmanage_patient_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmanage',
            name='create_by',
            field=models.CharField(default='doctor', max_length=64, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='patientmanage',
            name='update_by',
            field=models.CharField(default='doctor', max_length=64, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='patientmanage',
            name='patient_department',
            field=models.CharField(default='心电', max_length=60, verbose_name='检测类型'),
        ),
        migrations.AlterField(
            model_name='patientmanage',
            name='patient_describe',
            field=models.TextField(max_length=200, verbose_name='检测描述'),
        ),
    ]
