# Generated by Django 4.0 on 2023-04-08 09:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patientmanage_create_by_patientmanage_update_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmanage',
            name='patient_describe',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200, verbose_name='检测描述'),
        ),
    ]
